### ISSUE TITLE
Error when trying to run numpy

### ISSUE THREAD

**Issue by Neuro-Dynamics** [qpython-android/aipy#4]
/data/data/org.qpython.qpy/files/bin/qpython.sh "/storage/emulated/0/qpython/test.py" && exit
ython/test.py" && exit                  <
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/test.py", line 1, in <module>
    import numpy
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: dlopen failed: could not load library "libopenblas.so" needed by "multiarray.so"; caused by could not load library "libgfortran.so" needed by "libopenblas.so"; caused by cannot locate symbol "acoshf" referenced by "libgfortran.so"...

1|u0_a219@e5lte:/ $

Samsung Galaxy E5 (SM-E500M)
Android 4.4.4

Is there anything I can do to solve the problem?

**Comment by OlafHaag** [comment]
Around the time when this issue was opened I had the same problem (see #1 ). The vendor didn't provide updates to Android anymore, but when I was switched to Lineage OS based on a newer Android version, the problem disappeared.
