### ISSUE TITLE
keras.datasets.mnist.load_data() is not working,

### ISSUE THREAD

**Issue by talregev** [qpython-android/aipy#5]
Run keras with theano aipy over oneplus 3t with qpython and  aipy
`keras.datasets.mnist.load_data() ` is not working,
I set path='' argument to many paths and also download the npz file but still it want to go to /tmp folder that it read only.

In the end i download the file manually and open it with numpy. 
Can you fix that? 

```bash
/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/tal.py" && exit
ge/emulated/0/qpython/tal.py" && exit    <
Using Theano backend.
/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/theano/configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
( library_dirs = /data/user/0/org.qpython.qpy/files/lib )
( include_dirs = /data/user/0/org.qpython.qpy/files/include )
( library_dirs = /data/user/0/org.qpython.qpy/files/lib )
( library_dirs = /data/user/0/org.qpython.qpy/files/lib )
( library_dirs = /data/user/0/org.qpython.qpy/files/lib )
( library_dirs = /data/user/0/org.qpython.qpy/files/lib )
( library_dirs = /data/user/0/org.qpython.qpy/files/lib )
( library_dirs = /data/user/0/org.qpython.qpy/files/lib )
( library_dirs = /data/user/0/org.qpython.qpy/files/lib )
( src_dirs = . )
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/tal.py", line 18, in <module>
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/keras/datasets/mnist.py", line 23, in load_data
    file_hash='8a61469f7ea1b51cbae51d4f78837e45')
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/keras/utils/data_utils.py", line 182, in get_file
    os.makedirs(datadir)
  File "/data/user/0/org.qpython.qpy/files/lib/python27.zip/os.py", line 150, in makedirs
  File "/data/user/0/org.qpython.qpy/files/lib/python27.zip/os.py", line 150, in makedirs
  File "/data/user/0/org.qpython.qpy/files/lib/python27.zip/os.py", line 157, in makedirs
OSError: [Errno 30] Read-only file system: '/tmp'
1|OnePlus3T:/ $
```

**Comment by talregev** [comment]
I want change the title of the issue. is confusing.

mnist.load_data() is not working,
I try to give path='' many paths and also download the npz file  but still it want to go to /tmp folder that it read only.

**Comment by molgrumbler** [comment]
I have  the same problem. Is there any solution?
